### ISSUE TITLE
macOS High Sierra web-cli ./gradlew build failed with an exception. 

### ISSUE THREAD

**Issue by LingTian** [tronprotocol/tron-studio#2]
./gradlew build -x test -x check cause error.

FAILURE: Build failed with an exception.

Not fixed by similar method closed in web-cli. Still open.

**Comment by UnforgivenZZZ** [comment]
> ./gradlew build -x test -x check cause error.
> 
> FAILURE: Build failed with an exception.
> 
> Not fixed by similar method closed in web-cli. Still open.

which java version are you using? make sure it is Orcal jdk 1.8

**Comment by kookiekrak** [comment]
closing because i assume this is fixed. please reopen if not.
