### ISSUE TITLE
contract validate error : percent must be >= 0 and <= 100

### ISSUE THREAD

**Issue by rd1706** [tronprotocol/tron-studio#7]
When I try to deploy a contract, this error appears:

Code = CONTRACT_VALIDATE_ERROR
Message = contract validate error : percent must be >= 0 and <= 100

Win 10 64, Java 1.8.0_181-b13

**Comment by UnforgivenZZZ** [comment]
make sure the value you have in the user pat ratio field is some number between 0 and 100. if you dont want to have user pay ratio, just fill 0, do not leave it as empty string

**Comment by UnforgivenZZZ** [comment]
> When I try to deploy a contract, this error appears:
> 
> Code = CONTRACT_VALIDATE_ERROR
> Message = contract validate error : percent must be >= 0 and <= 100
> 
> Win 10 64, Java 1.8.0_181-b13

make sure the value you have in the user pat ratio field is some number between 0 and 100. if you dont want to have user pay ratio, just fill 0, do not leave it as empty string

**Comment by tmao1129** [comment]
Closing issue.
